### ISSUE TITLE
Sign In Duration

### ISSUE THREAD

**Issue by mbeinder** [okta/samples-ios#79] opened 2020-04-21 01:22 UTC
Running the browser signin code.

I cannot get the application to stay logged in for more than 1 hour. I’ve tried updating the token duration on the authorization server, but then that app crashes.

**Comment by IldarAbdullin-okta** [comment] 2020-05-15 20:31
Hi @mbeinder ,

Thanks for reporting this issue. Do you have call stack for the crash that you can share?

Ildar

**Comment by mbeinder** [comment] 2020-05-15 20:34
@IldarAbdullin-okta I am not an iOS developer so I’m not sure what that is. I know just enough to get around.

**Comment by IldarAbdullin-okta** [comment] 2020-07-10 21:27
@mbeinder , I was not able to reproduce the crash. If you work on preview environment probably you can create test account for me so I can try to replicate with your environment

**Comment by oleggnidets-okta** [comment] 2021-04-06 15:35
I cannot reproduce as well. Closing for now.

**Closed by oleggnidets-okta** 2021-04-06 15:35 UTC
